### ISSUE TITLE
how to align_annotations?

### ISSUE THREAD

**Issue by friendly** [luisDVA/annotater#12]
Thanks for a useful package.
Maybe I'm missing something, but the annotate package calls would be nicer if by default it aligned the annotations, e.g.,

    library(dplyr)          # A Grammar of Data Manipulation
    library(tidyr)          # Tidy Messy Data
    library(broom)          # Convert Statistical Objects into Tidy Tibbles
    library(modelr)         # Modelling Functions that Work with the Pipe
    library(distributional) # Vectorised Probability Distributions
    library(here)           # A Simpler Way to Find Your Files

There seems to be an `align_annotations()` function, but I have no idea how it can be used

**Comment by luisDVA** [comment]
Hi! 
At this point, only the `Annotate package repository sources` addin has alignment enabled by default, using `align_annotations` under the hood. This was intentional, since all annotations except for Repo + version tend to be quite long and often get wrapped across lines, ultimately breaking scripts. Aligning any of the longer strings that include a package title had too much disruptive potential. I'll think about maybe adding a separate function to toggle alignment, or simply to state all of this more clearly in the documentation.
