### ISSUE TITLE
"no matching library load calls" despite package functions seeming to be used normally

### ISSUE THREAD

**Issue by SimonDedman** [luisDVA/annotater#13]
I used the "annotate each package's function calls" addin successfully a couple of times before this happened, but now this error happens on multiple files, but not all. Example scripts attached (change extension to R).
Thanks!

[EddyAppendAVISO3_LongFiles.txt](https://github.com/luisDVA/annotater/files/8216996/EddyAppendAVISO3_LongFiles.txt)

[KUD.txt](https://github.com/luisDVA/annotater/files/8217002/KUD.txt)

**Comment by luisDVA** [comment]
Hi Simon, 
Thanks for raising this issue. I've found the problem.
You have whitespace before your `library()` calls at the start of each line. This may or may not be intentional in your code, but the regexp that matches library load calls for all the functions in the package currently doesn't allow for anything other than `"^library"`.

I'll fix this for the next release.

**Comment by SimonDedman** [comment]
Ah interesting. Certainly if called within a function the library() calls will indent that way naturally. Good job deducing the problem! Cheers!
