### ISSUE TITLE
not working on latest Rstudio (Version 1.4.1717)

### ISSUE THREAD

**Issue by verajosemanuel** [luisDVA/annotater#9]
using previous version everything was ok. Then upgraded to Version 1.4.1717 and error message window arises:

![Screenshot 2021-06-08 110704](https://user-images.githubusercontent.com/15836677/121157282-b2a11100-c849-11eb-818e-bcf5b3bdb0ee.png)

**Comment by luisDVA** [comment]
Thanks for bringing this up.
Other than that pop-up window are you getting an error message in the console?

The only way I can recreate that message in the latest RStudio is by running functions from the addin menu with the focus on the console rather than the open script.

If this is the case, this is normal. Let me know if this helps.
LD

**Comment by verajosemanuel** [comment]
opening an R file and calling from console:

```
annotater::annotate_active_file()
Error in annotater::annotate_active_file() : 
  Focus (blinking cursor) is not on an open R file
Run `rlang::last_error()` to see where the error occurred.


annotater::annotate_pkg_calls()
Error in match_pkg_names(string_og) : 
  argument "string_og" is missing, with no default
```

**Comment by luisDVA** [comment]
I've looked into this, and with R v 4.1.0 and RStudio 1.4.17 all the addins work correctly when used in an active file. At this point, only `annotate_script` is meant for running from the console, so I'll make sure to update the documentation to state this explicitly. Thanks again!
